
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-demo-project/locations/us-central1/spaces/default-space/applicationTemplates/app-template-1

module "cloud-run-1" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.33.0"
  project_id                    = var.cloud-run-1_project_id
  location                      = var.cloud-run-1_location
  service_name                  = var.cloud-run-1_service_name
  containers                    = var.cloud-run-1_containers
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = [module.cloud-run-1.apphub_service_uri]
  application_id = var.apphub_application_id
}
