
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-demo-project/locations/us-central1/spaces/default-space/applicationTemplates/app-template-1

variable "cloud-run-1_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-1_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "cloud-run-1_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "cloud-run-1_containers" {
  description = "Container images for the service"
  type = list(object({
    container_name       = optional(string, null)
    container_image      = string
    working_dir          = optional(string, null)
    depends_on_container = optional(list(string), null)
    container_args       = optional(list(string), null)
    container_command    = optional(list(string), null)
    env_vars             = optional(map(string), {})
    env_secret_vars = optional(map(object({
      secret  = string
      version = string
    })), {})
    volume_mounts = optional(list(object({
      name       = string
      mount_path = string
    })), [])
    ports = optional(object({
      name           = optional(string, "http1")
      container_port = optional(number, 8080)
    }), {})
    resources = optional(object({
      limits = optional(object({
        cpu        = optional(string)
        memory     = optional(string)
        nvidia_gpu = optional(string)
      }))
      cpu_idle          = optional(bool, true)
      startup_cpu_boost = optional(bool, false)
    }), {})
    startup_probe = optional(object({
      failure_threshold     = optional(number, null)
      initial_delay_seconds = optional(number, null)
      timeout_seconds       = optional(number, null)
      period_seconds        = optional(number, null)
      http_get = optional(object({
        path = optional(string)
        port = optional(string)
        http_headers = optional(list(object({
          name  = string
          value = string
        })), [])
      }), null)
      tcp_socket = optional(object({
        port = optional(number)
      }), null)
      grpc = optional(object({
        port    = optional(number)
        service = optional(string)
      }), null)
    }), null)
    liveness_probe = optional(object({
      failure_threshold     = optional(number, null)
      initial_delay_seconds = optional(number, null)
      timeout_seconds       = optional(number, null)
      period_seconds        = optional(number, null)
      http_get = optional(object({
        path = optional(string)
        port = optional(string)
        http_headers = optional(list(object({
          name  = string
          value = string
        })), [])
      }), null)
      tcp_socket = optional(object({
        port = optional(number)
      }), null)
      grpc = optional(object({
        port    = optional(number)
        service = optional(string)
      }), null)
    }), null)
  }))
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
